spring:
  profiles:
    active: local
    include: oauth
---
spring:
  config:
    activate:
      on-profile: local
  datasource:
    url: jdbc:mysql://localhost:3306/toyproject?serverTimezone=UTC
    username: team7-server
    password: velog
  sql:
    init:
      mode: always
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: create
    show-sql: true
---
spring:
  config:
    activate:
      on-profile: prod
  datasource:
    url: jdbc:mysql://waffle-team7-velog.chkd27eval6m.ap-northeast-2.rds.amazonaws.com:3306/toyproject?serverTimezone=UTC
    username: team7-server
    password: velog
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: update

---
spring:
  mail:
    host: smtp.gmail.com
    port: 587
    username: waflog.register@gmail.com
    password: wafflestudio123
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
---
spring:
    profiles:
        include:
            - aws

