name: Java CI with Gradle

on:
  push

jobs:
  CI:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./waflog

    steps:
    - uses: actions/checkout@v2

    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'
        cache: gradle

    - name: Set up MySQL
      run: |
        sudo service mysql start
        mysql -uroot -proot < ./scripts/sql/init-test-db.sql

    - name: Grant execute permission for gradlew
      run: chmod +x ./gradlew

    - name: Build with Gradle
      run: ./gradlew build -x test

    - name: Test with Gradle
      run: ./gradlew test
